name: Azure Container Instances Workflow
on:
  # push:
  workflow_dispatch:

jobs:
  azure-aci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v2.1.0
        with:
          client-id: ${{ secrets.AZURE_APP_REGISTRATION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID}}
          subscription-id: ${{ secrets.AZURE_SUBS_ID }}
        
