name: Azure Container Instances Workflow
on:
  push:
  workflow_dispatch:

env:
  AZURE_ACR_NAME: mydemoacrgithubactions
  AZURE_RESOURCE_GROUP: acr-resource-group
  IMAGE_NAME: node-farm
  AZURE_CONTAINER_GROUP_NAME: node-farm-container-group
  APPLICATION_PORT: 3000
  DNS_NAME: node-farm
jobs:
  azure-aci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        run: |
          az login --username ${{ secrets.AZURE_APP_REGISTRATION_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} --service-principal
        # uses: Azure/login@v2.1.0
        # with:
        # creds: ${{ secrets.AZURE_CREDS }}
      - name: Create Azure Container Registery
        run: |
          az acr create --name ${{ env.AZURE_ACR_NAME }}  --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --sku Basic
      - name: Authenticate to Azure Container Registery
        run: |
          az acr login --name ${{ env.AZURE_ACR_NAME }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.AZURE_ACR_NAME}}.azurecr.io/${{ env.IMAGE_NAME }}
      - name: Create Container Instance
        run: |
          az container create --name ${{ env.AZURE_CONTAINER_GROUP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --ports ${{env.APPLICATION_PORT}} --image ${{ env.AZURE_ACR_NAME}}.azurecr.io/${{ env.IMAGE_NAME }} --ip-address public --dns-name-label ${{ env.DNS_NAME }} --location centralus --registry-username ${{ secrets.AZURE_APP_REGISTRATION_ID }} --registry-password ${{ secrets.AZURE_CLIENT_SECRET }}
